add_library(${RH_ENV_TARGET} INTERFACE)
target_include_directories(${RH_ENV_TARGET}
        INTERFACE $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/include>
        )

install(TARGETS ${RH_ENV_TARGET}
        EXPORT ${RH_EXPORT_PREFIX}${RH_ENV_TARGET}${RH_EXPORT_SUFFIX}
        INCLUDES DESTINATION ${RH_INSTALL_INCLUDE_DIR}
        )

export(EXPORT ${RH_EXPORT_PREFIX}${RH_ENV_TARGET}${RH_EXPORT_SUFFIX}
        NAMESPACE ${RH_EXPORT_NAMESPACE}
        FILE ${RH_BUILD_CMAKE_DIR}/${RH_EXPORT_PREFIX}${RH_ENV_TARGET}${RH_EXPORT_SUFFIX}.cmake
        )
install(EXPORT ${RH_EXPORT_PREFIX}${RH_ENV_TARGET}${RH_EXPORT_SUFFIX}
        DESTINATION ${RH_INSTALL_CMAKE_DIR}
        NAMESPACE ${RH_EXPORT_NAMESPACE}
        )
